### ISSUE TITLE
MailParser - Encoding not issues

### ISSUE THREAD

**Issue by rzore** [rzore/Test#30]
NOTE: Only use this when you are filing a ticket for change management. Normal requests don't need to use this template, so you can delete everything and write whatever.

## DESCRIPTION OF CHANGE:

Issue 1: 

These are flooding the logs.  The newest version of mail parser should correct the logging and supporting iconv might lead to more understood encodings.  Albeit with a performance penalty.

22|generat | Error: Encoding not recognized: 'CHARSET=US-ASCII' (searched as: 'charsetusascii')
22|generat |     at Object.getCodec (/root/ds-feed-generator/node_modules/iconv-lite/lib/index.js:106:23)
22|generat |     at Object.getDecoder (/root/ds-feed-generator/node_modules/iconv-lite/lib/index.js:127:23)
22|generat |     at Object.decode (/root/ds-feed-generator/node_modules/iconv-lite/lib/index.js:40:25)
22|generat |     at convertIconvLite (/root/ds-feed-generator/node_modules/encoding/lib/encoding.js:91:26)
22|generat |     at Object.convert (/root/ds-feed-generator/node_modules/encoding/lib/encoding.js:43:26)
22|generat |     at MailParser._convertString (/root/ds-feed-generator/node_modules/mailparser/lib/mailparser.js:1358:25)
22|generat |     at MailParser._convertStringToUTF8 (/root/ds-feed-generator/node_modules/mailparser/lib/mailparser.js:1370:18)
22|generat |     at MailParser._finalizeContents (/root/ds-feed-generator/node_modules/mailparser/lib/mailparser.js:975:50)
22|generat |     at MailParser._processStateBody (/root/ds-feed-generator/node_modules/mailparser/lib/mailparser.js:382:26)
22|generat |     at MailParser._process (/root/ds-feed-generator/node_modules/mailparser/lib/mailparser.js:233:22)

Issue 2:

Error: Conversion from CP-850 to UTF-8//TRANSLIT//IGNORE is not supported.

Items to complete as part of this ticket:

* [ ] Will newest version of mail parser work with our system
* [ ] Will iconv imporve our ability to decode these formats.
* [ ] Verify logs are cleaned up.

|                                                                   | Yes      | No       |
|----|----|----|
| Can we clearly predict the outcome of the change?                 | Risk + 0 | Risk + 1 |
| Will this change be noticeable to customers?                      | Risk + 1 | Risk + 0 |
| Could this change inadvertently impact other services?            | Risk + 1 | Risk + 0 |
| Could this change result in extended service interruption?        | Risk + 1 | Risk + 0 |

**RISK ASSESSMENT SCORE:** 2

## TEST PLAN:

* Unit tests pass and the event schema output is not changed in a way that would impact.
* Logs are reduced given the same load.
* All effected services start and run without unhandled errors.

- - -
## Requirements
* [ ] Select Assignee
* [ ] Apply Applicable Labels
* [ ] Complete Risk Assessment
* [ ] Determine Approval or Denial & Apply Labels
* [ ] Apply Complete Label

**Comment by rzore** [comment]
➤ 250ok-mikeyoung commented:

Spent a little time on this and tried a new version of mailparser but it changes the format of the headers to an object for to, from, dkim.  So it changes the format the rest of the system may be expecting.

**Comment by rzore** [comment]
➤ 250ok-mikeyoung commented:

Posed this question to mail parser.

https://github.com/nodemailer/mailparser/issues/189
